#! /usr/bin/env python
from argparse import ArgumentParser
import zipfile

parser = ArgumentParser(
    description="""Helper script to convert wiseflow .""")
parser.add_argument("--config-file", type=str, action="store",
                    default="classroom-tool.cfg",
                    help="Location of classroom-tool config file.")
parser.add_argument("--log-level", type=str, action="store",
                    default="INFO",
                    help="Level of logging (defaults to INFO).")
parser.add_argument("--downloads-folder", type="str", action="store",
                    help="Folder containing downloaded wiseflow.")
args = parser.parse_args()

log_level = getattr(logging, args.log_level.upper(), None)
if not isinstance(log_level, int):
    raise ValueError('Invalid log level: %s' % args.log_level)
logging.basicConfig(level=args.log_level, format='%(asctime)s %(message)s')

configparser = ConfigParser()
configparser.read(args.config_file)

if not configparser.sections():
    configparser = None
    #raise ConfigError(f"Missing or empty config file: {args.config_file}")

